### ISSUE TITLE
API Create company account | Add invitation id and api for invitation details

### ISSUE THREAD

**Issue by SanaSalem01** [eclipse-tractusx/portal-backend#834] opened 2024-07-15 08:05 UTC
**Change proposal:**
Add Company Id,application id in response of ExecuteInvitation api i.e POST: api/administration/invitation

**Reason:**
In automation and CRM communication there was no reference id to track the Invitation.

**Current Impact/limitations:**
- The missing response information makes implementing APIs and integration tests more time-consuming.
- CRM communication there was no reference id to track the Invitation

**Change proposal impact:**
So now any system can use Application id and Company Id for reference after invitation.

**Comment by jjeroch** [comment] 2024-07-15 14:30
@SanaCofinityX  please update the ticket - this is a change proposal and not a bug (as it intends when reading the title" please use something like "API Create company account | adding "applicationID" in the response body" this makes it more open. Please also share the info if you want to contribute the code for it.

**Comment by SanaCofinityX** [comment] 2024-07-16 08:05
@jjeroch 
Ticket summary has been updated.

**Comment by tfjanjua** [comment] 2024-07-22 13:45
@jjeroch | @evegufy 
I would like to ask from which release branch I should checkout for this change!
I am assuming it would be https://github.com/eclipse-tractusx/portal-backend/tree/release/v2.1.0-RC1 but please let me know if there is any other release to checkout.

Thanks

**Comment by dhiren-singh-007** [comment] 2024-08-28 10:05
This api is creating the CompanyInvitation and it make sense to return the Id of CompanyInvitation only.
Because the whole process of creating this invitation is in background process so even if we move the application creation in api itself then one have to still wait for the completion of whole process.
So idea would be to use this invitation id to fetch the Company application Id and Company Id from a different new api (with same set of permissions as Invitation api have).
So far there are two use cases for this 

1. Automation: Automation test need to check the status of company application so it requires application id , which it don't have access in Invitation. So by this change they will be able to get the application id and company id.
2. Hubspot (CRM invitation for Self registration) : In this case CRM is unable to track the application as there is no reference Id so with this change they can use Invitation Id as reference and then they can call another api to get the application id and company id .
As this is a background process so in order to get the application id one has to wait for scheduled cron job frequency (currently its 5 min). 
cc @MaximilianHauer @SanaCofinityX @ybidois @tfjanjua

**Comment by dhiren-singh-007** [comment] 2024-09-05 09:01
UPDATE: As Because of the issue #700 . Company and application creation is moved in api execution itself so now we no longer need an api to retrieve these ids.
So I have updated the @Phil91 PR #960  with this change where Invite api will now return these ids .

**Comment by MaximilianHauer** [comment] 2024-09-06 20:29
@dhiren-singh-007  i assume this solves the ticket ?

**Comment by dhiren-singh-007** [comment] 2024-09-09 08:24
> @dhiren-singh-007 i assume this solves the ticket ?

Yes @MaximilianHauer , PR #960 will solve this once merged.

**Closed** 2024-09-17 14:41 UTC
Labels: Task, Improvement
